name: CI Build (.NET Core 3.1)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: Build packages
      run: dotnet pack EzEventPush/EzEventPush.sln -c Release -o out
    - name: Push shared package
      run: dotnet nuget push out/Push4711.Shared.*.nupkg -k ${{ secrets.NUGETORG_PKG_PUSH_SECRET }} -s https://api.nuget.org/v3/index.json --skip-duplicate --no-symbols true
    - name: Push sender package
      run: dotnet nuget push out/Push4711.Sender.*.nupkg -k ${{ secrets.NUGETORG_PKG_PUSH_SECRET }} -s https://api.nuget.org/v3/index.json --skip-duplicate --no-symbols true
    - name: Push receiver package
      run: dotnet nuget push out/Push4711.Receiver.*.nupkg -k ${{ secrets.NUGETORG_PKG_PUSH_SECRET }} -s https://api.nuget.org/v3/index.json --skip-duplicate --no-symbols true